[versions]
commonsLang3 = "3.18.0"
hivemq = "1.3.0"
mockk = "1.14.6"
springBoot = "3.5.5"

[libraries]
commonsLang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commonsLang3" }
hivemqMqttClient = { module = "com.hivemq:hivemq-mqtt-client", version.ref = "hivemq" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
