[versions]
jackson = "2.18.3"
hivemq = "1.3.0"
reactor = "3.7.9"
commonsLang3 = "3.18.0"
kotlin = "2.2.10"
kotlinxCoroutines = "1.10.2"
slf4j = "2.0.17"
springFramework = "6.2.10"
springBoot = "3.5.5"
mockk = "1.14.6"
assertj = "3.26.0"
junitJupiter = "5.10.1"
junitPlatform = "1.12.2"
springCloudStream = "4.3.0"

[libraries]
jacksonDatabind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
hivemqMqttClient = { module = "com.hivemq:hivemq-mqtt-client", version.ref = "hivemq" }
reactorCore = { module = "io.projectreactor:reactor-core", version.ref = "reactor" }
commonsLang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commonsLang3" }

kotlinStdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinxCoroutinesReactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "kotlinxCoroutines" }

slf4jApi = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

springContext = { module = "org.springframework:spring-context", version.ref = "springFramework" }
springWeb = { module = "org.springframework:spring-web", version.ref = "springFramework" }
springWebflux = { module = "org.springframework:spring-webflux", version.ref = "springFramework" }

springBoot = { module = "org.springframework.boot:spring-boot", version.ref = "springBoot" }
springBootStarterTest = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springBoot" }

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
assertjCore = { module = "org.assertj:assertj-core", version.ref = "assertj" }
kotlinTestJunit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
junitJupiterParams = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junitJupiter" }

reactorTest = { module = "io.projectreactor:reactor-test", version.ref = "reactor" }
springCloudStreamTestBinder = { module = "org.springframework.cloud:spring-cloud-stream-test-binder", version.ref = "springCloudStream" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatform" }
